# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RationOffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Fullname', models.CharField(max_length=20)),
                ('CardType', models.CharField(default='APL', max_length=3)),
                ('Verified', models.BooleanField(default=False)),
                ('RationCardNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('LastSentOTP', models.PositiveIntegerField(blank=True, null=True)),
                ('WheatBalance', models.FloatField()),
                ('RiceBalance', models.FloatField()),
                ('SugarBalance', models.FloatField()),
                ('KeroseneBalance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10)),
                ('price_APL', models.FloatField(default=0.0)),
                ('price_BPL', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RationShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopKeeper', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('NumberOfBPLCostumers', models.PositiveSmallIntegerField(default=0)),
                ('NumberOfAPLCostumers', models.PositiveSmallIntegerField(default=0)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RationOffice.RationOffice')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RationShop.RationShop'),
        ),
    ]
