# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RationShop', '0002_auto_20161104_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='KeroseneBalance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='RiceBalance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SugarBalance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='WheatBalance',
            field=models.FloatField(default=0.0),
        ),
    ]
