# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RationShop', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('Fullname', models.CharField(max_length=20)),
                ('Hashed', models.BooleanField(default=False)),
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rationshop',
            name='ShopKeeper',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RationShop.RationShop'),
        ),
    ]
