# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RationShop', '0005_auto_20161104_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limit_APL',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='limit_BPL',
            field=models.FloatField(default=0.0),
        ),
    ]
