# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RationShop', '0004_merge_20161104_2036'),
        ('RationShop', '0006_auto_20161104_2306'),
    ]

    operations = [
    ]
