# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=50)),
                ('NumberOfRationShops', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RationOfficer',
            fields=[
                ('FullName', models.CharField(max_length=20)),
                ('Hashed', models.BooleanField(default=False)),
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RationOffice.RationOffice')),
            ],
        ),
    ]
